### ISSUE TITLE
Is there an api to delete application versions

### ISSUE THREAD

**Issue by yahanvesh** [fortify/ssc-restapi-client#11]
We have observed issues for a certain application which now has 1120 versions, we would like to do version cleanup.
Im searching for an api for the same, but couldnt find in https://api.ams.fortify.com/swagger/ui/index#/

**Comment by akaryakina** [comment]
Hi. Yes, there is an API to delete the project version on the Fortify SSC server. It's part of ProjectVersionControllerApi: deleteProjectVersion. However, there are several considerations:
1. The link that you listed is for the FoD server API, not the SSC server. FoD is our On Demand service to analyze and audit your code remotely by uploading it to our server. SSC is our On Premise solution where you configure SCA scanning and analysis on your side without the code ever leaving your network. This github project is a swagger generated client for the On Premise server API.
2. Now, speaking of purging SSC application versions, there's that ProjectVersionControllerApi: deleteProjectVersion operation that can be scripted to delete all of your versions in an automated fashion. However, since deleting an appversion can be fairly heavy operation if there are lot of issues, it anyway makes sense to do it sequentially in a script and let it run overnight. 
You should ensure that no other operations are happening on those app versions at that time (and probably SSC activity in general) and also check completion of each delete operation.
